version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - singleCaseSwitch
    gosec:
      excludes:
        - G101
        - G115
        - G117
  exclusions:
    rules:
      - path: (_test\.go|mock\.go)
        linters:
          - gosec
          - errcheck

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(go.admiral.io)

run:
  timeout: 10m
  go: "1.25"

output:
  formats:
    text:
      print-linter-name: true
