version: 2

project_name: admiral

env:
  - GO111MODULE=on

gomod:
  proxy: true

git:
  tag_sort: -version:refname

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

snapshot:
  version_template: "{{ incpatch .Version }}-next"

report_sizes: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
      - s390x
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=admiral

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}

docker_signs:
  - cmd: cosign
    artifacts: images
    output: true
    args:
      - sign
      - --yes
      - ${artifact}@${digest}

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: >-
      {{ .ProjectName }}-{{ .Version }}_{{ title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if and (eq .Os "darwin") (eq .Arch "all") }}universal
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - README.md
      - LICENSE
      - completions/*

homebrew_casks:
  - name: admiral
    binaries:
      - admiral
    completions:
      bash: completions/admiral.bash
      zsh: completions/admiral.zsh
      fish: completions/admiral.fish
    homepage: https://admiral.io/
    description: Admiral CLI - Platform Orchestrator
    dependencies:
      - formula: git
    commit_author:
      name: admiral-ci
      email: support@admiral.io
    repository:
      owner: DataliftHQ
      name: homebrew-tap

dockers_v2:
  - images:
      - "ghcr.io/datalifthq/admiral"
    tags:
      - "{{ .Tag }}"
      - latest
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "io.artifacthub.package.maintainers": '[{"name":"Admiral","email":"support@admiral.io"}]'
      "io.artifacthub.package.license": "MPL-2.0"
      "org.opencontainers.image.description": "Admiral - Platform Orchestrator CLI"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    extra_files:
      - scripts/entrypoint.sh

nfpms:
  - id: admiral
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: Admiral <support@admiral.io>
    description: Admiral CLI - Platform Orchestrator
    homepage: https://admiral.io
    license: MPL-2.0
    vendor: Admiral
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/admiral.bash
        dst: /usr/share/bash-completion/completions/admiral
        file_info:
          mode: 0644
      - src: ./completions/admiral.fish
        dst: /usr/share/fish/vendor_completions.d/admiral.fish
        file_info:
          mode: 0644
      - src: ./completions/admiral.zsh
        dst: /usr/share/zsh/vendor-completions/_admiral
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/admiral/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    dependencies:
      - git
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

scoops:
  - name: admiral
    repository:
      owner: DataliftHQ
      name: scoop-bucket
    directory: bucket
    homepage: https://admiral.io
    description: |
      Admiral - Platform Orchestrator CLI for managing clusters, runners,
      and service accounts.
    license: MPL-2.0
    commit_author:
      name: admiral-ci
      email: support@admiral.io

sboms:
  - artifacts: archive

milestones:
  - close: true

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/DataliftHQ/admiral-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## Helping out

    This release is only possible thanks to **all** the support of some **awesome people**!
